# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 668e2f2aa315e9c9b54845c922effa4099b775d6ce452ffd8d9f11d1660440042d5e666409a670357678408150e38d9c183a023756f6994ff307bd37d5d23757

test:
  secret_key_base: 201635cff4dccd301fbd6ef0edf907b496eb2df70e22fbc0b06d59f58f8a4b6d0522ba1862cf7c6f035e354cb92efd33007e6ea165d7a16d088c58bb50da0c0d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
